[package]
name = "oif_starknet"
version = "0.1.0"
edition = "2024_07"

[dependencies]
alexandria_bytes = "0.4.0"
alexandria_encoding = "0.4.0"
contracts = { git = "https://github.com/hyperlane-xyz/hyperlane-starknet.git", subdirectory = "cairo/crates/contracts" }
mocks = { git = "https://github.com/hyperlane-xyz/hyperlane-starknet.git", subdirectory = "cairo/crates/mocks" }
openzeppelin_token = "0.20.0"
openzeppelin_access = "0.20.0"
openzeppelin_account = "0.20.0"
openzeppelin_introspection = "0.20.0"
openzeppelin_upgrades = "0.20.0"
openzeppelin_utils = "0.20.0"
permit2 = { git = "https://github.com/NethermindEth/permit2-starknet.git" }
starknet = ">=2.10.1"
token = { git = "https://github.com/hyperlane-xyz/hyperlane-starknet.git", subdirectory = "cairo/crates/token" }

[dev-dependencies]
snforge_std = "0.38.3"
assert_macros = ">=2.10.1"

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
